channels:
  - conda-forge
  - pytorch-nightly
dependencies:
  - python
  - pip
  - ipython
  - ipykernel
  - nbformat
  - matplotlib
  - tensorboard
  - ruff
  - pip:
    - jax[cpu]
    - flax
  - pytorch-nightly::pytorch
  - pytorch-nightly::torchvision
  - pytorch-nightly::cpuonly
